In [5]:
import pandas as pd

df_test = pd.read_csv('./datasets/alarm/test.csv')
df_train = pd.read_csv('./datasets/alarm/train.csv')

display(df_test.head())
display(df_train.head())

print(df_test.isnull().sum())
# print(df_train.isnull().sum())

,LVFAILURE,HISTORY,LVEDVOLUME,CVP,PCWP,HYPOVOLEMIA,STROKEVOLUME,ERRLOWOUTPUT,HRBP,HR,...,PRESS,KINKEDTUBE,VENTTUBE,MINVOLSET,VENTMACH,DISCONNECT,CATECHOL,INSUFFANESTH,CO,BP
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,...,3.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,2.0,0.0
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,...,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,1.0,1.0
2,1.0,1.0,2.0,2.0,2.0,0.0,1.0,1.0,2.0,2.0,...,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,...,3.0,0.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0
4,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,2.0,2.0,...,3.0,1.0,0.0,1.0,2.0,0.0,1.0,1.0,2.0,0.0

,LVFAILURE,HISTORY,LVEDVOLUME,CVP,PCWP,HYPOVOLEMIA,STROKEVOLUME,ERRLOWOUTPUT,HRBP,HR,...,PRESS,KINKEDTUBE,VENTTUBE,MINVOLSET,VENTMACH,DISCONNECT,CATECHOL,INSUFFANESTH,CO,BP
0,1,1,2,2,2,0,1,1,0,1,...,3,1,0,0,1,1,0,1,1,2
1,1,1,2,2,1,0,0,1,2,2,...,1,1,1,1,2,1,1,1,0,1
2,1,1,1,1,1,1,1,1,0,1,...,2,1,1,1,2,1,1,0,0,0
3,1,1,1,1,1,1,1,1,2,2,...,3,1,1,1,2,1,1,1,2,1
4,1,1,2,2,2,1,1,1,2,2,...,1,1,1,1,2,1,1,1,2,2

LVFAILURE       10
HISTORY         14
LVEDVOLUME      17
CVP             10
PCWP             7
HYPOVOLEMIA     12
STROKEVOLUME    15
ERRLOWOUTPUT     8
HRBP             6
HR              11
ERRCAUTER        7
HREKG           12
HRSAT           16
ANAPHYLAXIS     12
TPR             10
ARTCO2          15
EXPCO2          14
VENTLUNG        10
INTUBATION      10
MINVOL          13
FIO2             9
PVSAT            7
VENTALV         12
SAO2            12
SHUNT            8
PULMEMBOLUS     12
PAP             18
PRESS           12
KINKEDTUBE      11
VENTTUBE        10
MINVOLSET       16
VENTMACH         7
DISCONNECT       7
CATECHOL        10
INSUFFANESTH    11
CO              11
BP              10
dtype: int64